// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_hhD9Vh9UGeuX098s7HLcZx911eoJZ2A',
    appId: '1:399401442767:web:5cf89b71579c170f1d46ba',
    messagingSenderId: '399401442767',
    projectId: 'ejempo-login',
    authDomain: 'ejempo-login.firebaseapp.com',
    databaseURL: 'https://ejempo-login-default-rtdb.firebaseio.com',
    storageBucket: 'ejempo-login.firebasestorage.app',
    measurementId: 'G-M9G5MM801B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5UiYrf9mbkGvYjf65VctjqPa_1QIUp7A',
    appId: '1:399401442767:android:c5fc3af86a969e141d46ba',
    messagingSenderId: '399401442767',
    projectId: 'ejempo-login',
    databaseURL: 'https://ejempo-login-default-rtdb.firebaseio.com',
    storageBucket: 'ejempo-login.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcugP0ZsaoTMEN4fbvfhCSWlTmh4ub-t0',
    appId: '1:399401442767:ios:d7484b14e17826ae1d46ba',
    messagingSenderId: '399401442767',
    projectId: 'ejempo-login',
    databaseURL: 'https://ejempo-login-default-rtdb.firebaseio.com',
    storageBucket: 'ejempo-login.firebasestorage.app',
    iosClientId: '399401442767-jrk3kova1nqm8gtllauv7g6b1qvulsfb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcugP0ZsaoTMEN4fbvfhCSWlTmh4ub-t0',
    appId: '1:399401442767:ios:d7484b14e17826ae1d46ba',
    messagingSenderId: '399401442767',
    projectId: 'ejempo-login',
    databaseURL: 'https://ejempo-login-default-rtdb.firebaseio.com',
    storageBucket: 'ejempo-login.firebasestorage.app',
    iosClientId: '399401442767-jrk3kova1nqm8gtllauv7g6b1qvulsfb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_hhD9Vh9UGeuX098s7HLcZx911eoJZ2A',
    appId: '1:399401442767:web:6518c1b6a44ea7491d46ba',
    messagingSenderId: '399401442767',
    projectId: 'ejempo-login',
    authDomain: 'ejempo-login.firebaseapp.com',
    databaseURL: 'https://ejempo-login-default-rtdb.firebaseio.com',
    storageBucket: 'ejempo-login.firebasestorage.app',
    measurementId: 'G-E7ELMD0SGZ',
  );

}