// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYr2BK3ERM1UAf33lMjrXQr8RmTlFvgBw',
    appId: '1:285149567188:web:e67d5709676c7748774341',
    messagingSenderId: '285149567188',
    projectId: 'roll-and-reserve',
    authDomain: 'roll-and-reserve.firebaseapp.com',
    storageBucket: 'roll-and-reserve.firebasestorage.app',
    measurementId: 'G-5WEYV99J0B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP6SV19fg6hQkpx4SNL-50RvnNXY2Z1IU',
    appId: '1:285149567188:android:3bcfbb020855df58774341',
    messagingSenderId: '285149567188',
    projectId: 'roll-and-reserve',
    storageBucket: 'roll-and-reserve.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1upZhz_PjomewtGnIA1Gc6EzGVbEQcFo',
    appId: '1:285149567188:ios:42365b0c3b422a73774341',
    messagingSenderId: '285149567188',
    projectId: 'roll-and-reserve',
    storageBucket: 'roll-and-reserve.firebasestorage.app',
    iosClientId: '285149567188-g3cub2dcnil6p5rkin1ic3honn6j4u12.apps.googleusercontent.com',
    iosBundleId: 'com.example.rollAndReserve',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1upZhz_PjomewtGnIA1Gc6EzGVbEQcFo',
    appId: '1:285149567188:ios:42365b0c3b422a73774341',
    messagingSenderId: '285149567188',
    projectId: 'roll-and-reserve',
    storageBucket: 'roll-and-reserve.firebasestorage.app',
    iosClientId: '285149567188-g3cub2dcnil6p5rkin1ic3honn6j4u12.apps.googleusercontent.com',
    iosBundleId: 'com.example.rollAndReserve',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYr2BK3ERM1UAf33lMjrXQr8RmTlFvgBw',
    appId: '1:285149567188:web:1a742908bff7d7be774341',
    messagingSenderId: '285149567188',
    projectId: 'roll-and-reserve',
    authDomain: 'roll-and-reserve.firebaseapp.com',
    storageBucket: 'roll-and-reserve.firebasestorage.app',
    measurementId: 'G-7Y6XDP98TK',
  );

}